language: php

sudo: required

addons:
  postgresql: "9.4"

cache:
  directories:
  - $HOME/.composer/cache

php:
- 5.6
- 7.0

env:
  global:
  - DB=pgsql
  matrix:
  - MOODLE_BRANCH=MOODLE_31_STABLE
  - MOODLE_BRANCH=MOODLE_32_STABLE
  - MOODLE_BRANCH=MOODLE_33_STABLE
  - MOODLE_BRANCH=MOODLE_34_STABLE
  - MOODLE_BRANCH=MOODLE_35_STABLE
  - MOODLE_BRANCH=master

matrix:
  include:
  # Some additional tests including MOODLE 27..30 and php 5.5.
  # This plugin is not database intensive, just a few tests in mysqli should be enough.
  - php: 5.5
    env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=master
  # Test with PHP 7.1
  - php: 7.1
    env: DB=pgsql MOODLE_BRANCH=master
  # Moodle 3.4+ requires PHP 7.
  exclude:
  - php: 5.6
  - MOODLE_BRANCH=master

before_install:
- cd ../..
- composer selfupdate
- composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- moodle-plugin-ci install -vvv

script:
- php moodle/local/envbar/tests/privacy/privacy.php
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci csslint
- moodle-plugin-ci shifter
- moodle-plugin-ci jshint
- moodle-plugin-ci validate
- moodle-plugin-ci phpunit
- moodle-plugin-ci behat
